services:
  - type: web
    name: shopping-website
    env: java
    plan: free
    
    buildCommand: "mvn clean package -DskipTests"
    startCommand: "java -jar target/Shopping-Website-0.0.1-SNAPSHOT.jar"
    
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: shopping-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: shopping-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: shopping-db
          property: password

databases:
  - name: shopping-db
    plan: free
    databaseName: prada
    user: prada_user
